---
title: '5'
author: "Ryan Wang"
date: "2023-09-04"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE,
                      warning = FALSE)

library(tidyverse)
library(tidymodels)
library(dplyr)
library(here)
library(zoo)
library(tseries)
library(stats)
library(astsa)
library(forecast)
library(car)
library(MASS)
library(finalfit) 
library(ggplot2)
library(forecast)
library(lubridate)
library(astsa)
library(dynlm)
library(knitr)
library(nlme)

library(lubridate)
library(janitor)
library(vegan)
library(here)
library(RColorBrewer)
library(Polychrome) 

WI_ID <- read.csv(here("data", "WI_IDs_togenus.csv"))
```

```{r}
WI_1 <- WI_ID %>% 
  dplyr::select("deployment_id", "class", "common_name", "date", "time", "number_of_objects", "behavior")

ggplot(WI_1, aes(x=reorder(deployment_id,deployment_id,
                      function(x)+length(x)))) + geom_bar()+ coord_flip() + labs(x = 'Locations')

ggplot(WI_1, aes(x=reorder(class,class,
                      function(x)+length(x)))) + geom_bar()+ coord_flip() + labs(x = 'Class')

ggplot(WI_1, aes(x=reorder(common_name,common_name,
                                function(x)+length(x)))) + geom_bar()+ coord_flip() + labs(x = 'Common name')
```

```{r}
mammals <- WI_ID %>% filter(class == "Mammalia")

mammals <- WI_ID %>% 
  filter(class == "Mammalia") %>% 
  separate(behavior, c("behavior1", "behavior2"), sep = ",", remove = TRUE) %>% 
  mutate(ID = case_when(common_name == "Canis Species" ~ "Coyote",
                        common_name == "Cervus Species" ~ "Mule Deer",
                        common_name == "Odocoileus Species" ~ "Mule Deer",
                        common_name == "Elk" ~ "Mule Deer", # def not an elk
                        common_name == "Vulpes Species" ~ "Grey Fox",
                        common_name == "Lepus Species" ~ "Brush Rabbit", 
                        common_name == "Domestic Cat" ~ "Bobcat", # double checked, def a bobcat
                        common_name == "Domestic Pig" ~ "Feral Hog", 
                        common_name == "Wild Boar" ~ "Feral Hog",
                        common_name == "Sus Species" ~ "Feral Hog",
                        common_name == "Neotoma Species" ~ "Rat",
                        common_name == "Martes Species" ~ "Weasel",
                        common_name == "Ursus Species" ~ "American Black Bear",
                        common_name == "Nutria" ~ "Rat", # for now, until we determine if that thing is actually a nutria!
                        common_name == "Western Gray Squirrel" ~ "California Ground Squirrel",
                        common_name == "Brown Rat" ~ "Rat",
                        common_name == "Kit Fox" ~ "Coyote", # def not a kit fox 
                        common_name == "White-tailed Deer" ~ "Mule Deer",
                        common_name == "Domestic Cattle" & deployment_id == "Jalama 2" ~ "Feral Hog", # went and checked and computer IDd some pigs as cows. fixing for now in post, will fix later in WI [4aug23]
                        common_name == "White-tailed Jackrabbit" ~ "Coyote",
                        common_name == "Black-tailed Jackrabbit" ~ "Coyote",
                        TRUE ~ as.character(common_name))) %>% 
# need to remove sheep, mouflon?? and other weird IDs
  filter(ID != "Mouflon", 
         ID != "Domestic Sheep",
         ID != "Equus Species",
         ID != "Domestic Dog",
         ID != "Domestic Horse") %>% 
  filter(year != (2017))

count_species <- mammals%>%
  count(ID) # makes a summary table of # animal-seconds per species per deployment_id per month

######### plot #########

countbyspecies <- ggplot(count_species, aes(x = reorder(ID, -n), n)) + # reorders so that it displays bars in descending order of count
  geom_bar(stat = "identity") + # so i can pass a value to the bar instead of having ggplot count for me
  theme_classic()+
  theme(axis.text.x = element_text(angle = 45, 
                                   hjust = 1, 
                                   size = 7),
        axis.text.y = element_text(size = 10),
        axis.title.y = element_text(size = 10),
        axis.title.x = element_blank())+
  ylab("Number of Sightings")+
  xlab("Species")

countbyspecies

IDcolors <- alphabet.colors(16)
swatch(IDcolors)
names(IDcolors) <- NULL 

count_species_site_adj <- mammals %>% 
  group_by(deployment_id) %>% 
  mutate(trapdays = as.Date(max(mammals$date)) - as.Date(min(mammals$date))) %>% 
  group_by(deployment_id, trapdays) %>% 
  count(ID) %>% 
  mutate(adjusted_count = n/as.numeric(trapdays))

stacked <- ggplot(count_species_site_adj, aes(deployment_id, adjusted_count)) +
  geom_bar(aes(fill = ID), # lets me make clustered bar chart
           stat = "identity", # idk but necessary
           #position = "dodge" # otherwise default is stacked barchart
           )+
  scale_fill_manual(values = IDcolors)+
  theme_classic()+ 
  coord_flip() + # make it horizontal because its easier to vis
  scale_y_reverse(lim = c(1,0))+ # puts bars on the right side instead of the left
  #temporarily limiting x axis for better visualization of shorter bars, need to reverse order of coords
  scale_x_discrete(lim= rev) + # orients sites north to south instead of south to north
  
  ylab("Sightings Adjusted by Number of Trap Nights")+
  xlab("Sites North to South")+
  theme(#axis.text.y = element_blank(),
        axis.text.y = element_text(angle = 45, hjust = 1, size = 7), # only keep in for my own visualization
        axis.text.x = element_text(size = 20),
        axis.title.x = element_text(size = 20),
        axis.title.y = element_blank())+
  theme(
    panel.background = element_rect(fill='transparent'), #transparent panel bg
    plot.background = element_rect(fill='transparent', color=NA), #transparent plot bg
    panel.grid.major = element_blank(), #remove major gridlines
    panel.grid.minor = element_blank(), #remove minor gridlines
    legend.background = element_rect(fill='transparent'), #transparent legend bg
    legend.box.background = element_rect(fill='transparent') #transparent legend panel
  )

stacked
```


